# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder

WORKDIR /app

# Copy dependency definitions
COPY package.json package-lock.json ./

# Install dependencies, including production and dev
RUN npm install

# Copy source files and configuration
COPY tsconfig.json ./
COPY src ./src

# Build the project
RUN npm run build

FROM node:lts-alpine

WORKDIR /app

# Copy built files and node_modules from builder stage
COPY --from=builder /app/package.json ./
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["node", "build/index.js"]
